### ISSUE TITLE
Pre-testing checklist

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/plh-facilitator-app-mx-content#27]
- [x] Ensure draft articles are filtered out https://github.com/IDEMSInternational/plh-facilitator-app-content/issues/50
- [x] Update content on Crowdin
- [x] Make English language setting available (default stays Spanish)
- [x] Ensure onboarding_cc article is working 
- [x] Fix day_3_mh_stress_self_talk faqs
- [x] Confirm states are working as required
- [x] Send Google Play link to Laurie: https://play.google.com/store/apps/details?id=international.idems.plh_facilitator_mx
- [x] Ensure whatsapp reporting forms are displaying
- [x] Include PDFs when available 
     "Training manuals",  probably in Spanish and English. Follow `plh_facilitator_my` setup as an example of how to ensure the language dependency works
- [x] Ensure supervisor_name is working as required (included in https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/pull/31)
- [x] Include NIP logo
- [ ] #43
    - Laurie's description: Exactly the same as the supervisor name - it's a text field in some of the safeguarding articles that refers to a hotline or phone number that the facilitator can use and that number varies by state of the facilitator
    - State field: `user_state`
    - [State data list ](https://docs.google.com/spreadsheets/d/1oXTqpT5F7tYkgqChUR3ARwFFll_wbMvKy_Y-SLuLAJ4/edit#gid=1126793308)
    - [safeguard_resource global and overrides](https://docs.google.com/spreadsheets/d/1JOBfFWK5NnSOlsSmN7JlI5o3cA-216ig2gH_AZmIhAI/edit#gid=576010168)
    - State is set in `profile_about` template (navigate to Profile > About You)
    - Set-up included in #33, all that remains is to populate the [sheets](https://docs.google.com/spreadsheets/d/1JOBfFWK5NnSOlsSmN7JlI5o3cA-216ig2gH_AZmIhAI/edit#gid=576010168) with the actual phone numbers/contact details
- [x] Include partial translations to ensure they are working in principle: #32 
- [x] Include translations when available
- [x] Release

N.B. both `@global.safeguard_resource` and `@global.supervisor_name` require a browser-tab refresh or a Play Store app close/reopen to update correctly

**Comment by esmeetewinkel** [comment]
Closing this since only remaining issue is opened as separate issue
