### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/plh-facilitator-app-mx-content#44]
- [x] Finalise English content
- [x] Finalise additional assets
- [x] Sync content
- [x] Sync assets
- [x] Update Crowdin with updated English content
- [x] Sync translations into the app
- [x] Release

**Comment by esmeetewinkel** [comment]
From @lauriemarkle: 

- Translation will be completed March 5th. 
- Videos & 1 illustration will be updated by March 7th. 
- We'll should be ready to publish App on March 8th
