### ISSUE TITLE
iOS testing issues

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/plh-facilitator-app-mx-content#54]
### Testing link
https://appetize.io/app/sqd4ghzfbdq5n7cerawfr32yim?device=iphone14pro&osVersion=16.2
### Issues
- [x] Custom splash screen and app icon https://github.com/IDEMSInternational/parenting-app-ui/issues/2241
        **Essential**
        <img width="276" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/assets/74557272/bfd76444-431f-447f-b6b0-099c4a25f4d2">   <img width="158" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/assets/74557272/6e8f4924-2547-4967-9a71-377974ff49a2">

- [x] Full screen pop ups intersect native device status bar https://github.com/IDEMSInternational/parenting-app-ui/issues/2263
    **Essential**
    <img width="161" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/assets/74557272/4868c746-fb3b-4d09-aa8a-6e363a8100d1">

- [ ] Native device status bar text shows in black on top of dark blue header (not readable)
   **Not essential** since we're opting for a [white/colourless header by default](https://github.com/IDEMSInternational/plh-facilitator-app-content/issues/56#issuecomment-2020555259)
   <img width="162" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/assets/74557272/65d8cedb-8c48-4e7c-af3d-b061f5caf936">

- [x] Footer icons disappear https://github.com/IDEMSInternational/parenting-app-ui/issues/2243
   **Essential**
   
- [ ] User needs to accept notifications even though this app doesn't send notifications https://github.com/IDEMSInternational/parenting-app-ui/issues/2265
   **Not essential** but worth getting done if quick
   <img width="175" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/assets/74557272/be94bde3-e65f-4642-ac31-b6ade7e3fff9">

**Comment by lauriemarkle** [comment]
- [ ] Full screen overlay of T&Cs and Privacy Policy prevent exit back into the app. 
<img width="408" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/assets/74552270/5c304109-661c-4edc-aaf7-a1348d0e4e51">

**Comment by lauriemarkle** [comment]
- [ ] Adding parents to your parent group is not visible:
<img width="333" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/assets/74552270/f76ef6a8-6c73-4b64-a33f-83b78b4db135">

**Comment by lauriemarkle** [comment]
- [ ] Footer inconsistently loads and is slow to appear
<img width="333" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/assets/74552270/e075dc9d-241c-492c-b8ca-21570e01036d">

**Comment by esmeetewinkel** [comment]
> * [ ]  Adding parents to your parent group is not visible:
> 
> <img alt="image" width="333" src="https://private-user-images.githubusercontent.com/74552270/317833859-f76ef6a8-6c73-4b64-a33f-83b78b4db135.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNjUyMjEsIm5iZiI6MTcxMjA2NDkyMSwicGF0aCI6Ii83NDU1MjI3MC8zMTc4MzM4NTktZjc2ZWY2YTgtNmM3My00YjY0LWEzM2YtODNiNzhiNGRiMTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDEzMzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2OWRkNzk3YWI5YzU3NjgwYjZmNGZmN2JjZDBiMGM4ZTY4YmNlYzc4OGNmN2JkYzQ3OGJkZTUxMGM0ODM1OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yX25i9PYK0eXeX_9i-o-EgZPck5jjdcUL-q8d5-0hN0">

Closed by https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/pull/56#discussion_r1547890801

**Comment by esmeetewinkel** [comment]
> [ ] Buttons have a shadow on the font that is inconsistent with theme.

See https://github.com/IDEMSInternational/parenting-app-ui/issues/2287

**Comment by esmeetewinkel** [comment]
Closing here since remaining issues are not a priority to resolve / tracked on code repo
